export default {
    THEME_INIT: 'THEME_INIT',
    LANGUAGE_LOAD_SUCCESS: 'LANGUAGE_LOAD_SUCCESS',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    USER_UPDATE_NAME_SUCCESS: 'USER_UPDATE_NAME_SUCCESS',
    USER_UPDATE_NAME_FAIL: 'USER_UPDATE_NAME_FAIL',
    TEAM_CREATE_SUCCESS: 'TEAM_CREATE_SUCCESS',
    TEAM_CREATE_FAIL: 'TEAM_CREATE_FAIL',
    TEAM_LIST_SUCCESS:'TEAM_LIST_SUCCESS',
    TEAM_LIST_FAIL:'TEAM_LIST_FAIL',
    TEAM_SEARCH_SUCCESS:'TEAM_SEARCH_SUCCESS',
    TEAM_SEARCH_FAIL:'TEAM_SEARCH_FAIL'
}